FROM golang:buster

ENV GO111MODULE=on \
    GOOS=linux \
    GOARCH=amd64

EXPOSE 8080

# Set the Current Working Directory inside the container
WORKDIR /app

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

# Build the Go app
RUN go build -ldflags="-w -s"

# This container exposes port 8080 to the outside world


# Run the binary program produced by `go install`
ENTRYPOINT ["./togo-task"]