# vim: noai:sw=2:ts=2
version: "3.9"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: todo-service
    env_file: .env
    networks:
      - todo-net
    ports:
      - "8888:8080"

networks:
  todo-net:
    name: todo-net

